# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: $REGISTRY_URL/library/docker:latest

stages:
  - build
  - deploy

before_script:
  - docker login --username "$REGISTRY_LOGIN" --password "$REGISTRY_PASSWORD" $REGISTRY_URL

build:
  stage: build
  script:
    - docker build -f dockerfiles/Dockerfile_bot --tag $REGISTRY_URL/zabbixbot/zabbixbot_py3-bot:$CI_COMMIT_BRANCH .
    - docker push $REGISTRY_URL/zabbixbot/zabbixbot_py3-bot:$CI_COMMIT_BRANCH
    - docker build -f dockerfiles/Dockerfile_send --tag $REGISTRY_URL/zabbixbot/zabbixbot_py3-send:$CI_COMMIT_BRANCH .
    - docker push $REGISTRY_URL/zabbixbot/zabbixbot_py3-send:$CI_COMMIT_BRANCH

deploy-master:
  stage: deploy
  script:
    - echo "$SSH_KEY" > key
    - chmod 0400 key
    - ssh -o StrictHostKeyChecking=no -i key $USERNAME@$HOSTNAME 'bash zabbixbot.sh'
  only:
    - master
